Load_List:
  - {type: Unauthorized, loaded: true, re: nacos, method: GET, name: Nacos, id: 1, state: '200',
     url: /nacos/index.html, info: Nacos Find!!!}
  - { type: Unauthorized, loaded: true, re: 'GraphQL', method: GET, name: graphql, id: 1, state: '200',
      url: /graphql, info: graphql!!! }
  - {type: Spring, loaded: true, re: springframework|spring.cloud.bootstrap.location|Spring
    Actuator Env RCE, method: GET, name: Spring Env RCE, id: 2, state: '200', url: /env,
    info: 'Actuator Env|RCE:spring.cloud.bootstrap.location|XStreamRCE:eureka.client.serviceUrl.defaultZone
    Find!!!'}
  - {type: Spring, loaded: true, re: springframework|spring.cloud.bootstrap.location|Spring
    Actuator Env RCE, method: GET, name: Spring Env RCE, id: 3, state: '200', url: /actuator/env,
    info: 'Actuator Env|RCE:spring.cloud.bootstrap.location|XStreamRCE:eureka.client.serviceUrl.defaultZone
    Find!!!'}
  - {method: GET, state: '200', name: Druid Monitor, url: /druid/index.html, id: 4,
     info: Druid Monitor Find!!!, loaded: true, type: Unauthorized, re: druid}
  - {type: ApiDoc, loaded: true, re: api-docs, method: GET, name: api-docs, id: 5, state: '200',
     url: /v2/api-docs, info: api-docs Find!!!}
  - {type: ApiDoc, loaded: true, re: Swagger UI, method: GET, name: Swagger-UI, id: 6,
     state: '200', url: /swagger-ui.html, info: Swagger-UI Find!!!}
  - {type: Spring, loaded: true, re: springframework|reloadByURL|createJNDIRealm, method: GET,
     name: Spring Jolokia|Rce, id: 7, state: '200', url: /jolokia/list, info: 'Spring
    Jolokia|XXE/RCE:reloadByURL|RCE:createJNDIRealm Find!!!'}
  - {type: Spring, loaded: true, re: springframework|reloadByURL|createJNDIRealm, method: GET,
     name: Spring Jolokia|Rce, id: 8, state: '200', url: /actuator/jolokia/list, info: 'Spring
    Jolokia|XXE/RCE:reloadByURL|RCE:createJNDIRealm Find!!!'}
  - {type: Spring, loaded: true, re: swagger, method: GET, name: Swagger-resources,
     id: 12, state: '200', url: /swagger-resources, info: swagger-resources Find!!!}
  - {type: ApiDoc, loaded: true, re: ASP.NET|tempuri.org, method: GET, name: Soap, id: 13,
     state: '200', url: /services, info: Soap Find!!!}
  - {type: Information leakage, loaded: true, re: .git, method: GET, name: .Git, id: 17,
     state: '200', url: /.git/HEAD, info: .git Find!!!}
  - {type: Information leakage, loaded: true, re: -props|svn://, method: GET, name: Svn,
     id: 18, state: '200', url: /.svn/entries, info: .svn Find!!!}
  - {type: ApiDoc, loaded: true, re: api-docs|openapi, method: GET, name: api-docs,
     id: 24, state: '200', url: /v3/api-docs, info: api-docs Find !!!}
  - {type: Information leakage, loaded: true, re: 'User-agent: *', method: GET, name: robots,
     id: 25, state: '200', url: /robots.txt, info: robots.txt Find !!!}
  - {type: Spring, loaded: true, re: '{"_links":{"self":{"href"', method: GET, name: actuator, id: 26, state: '200',
     url: /actuator/, info: actuator FInd !!!}
  - {loaded: true, re: DWR Test Index, method: GET, name: dwr, id: 27, state: '200',
     type: Unauthorized, url: /dwr/index.html, info: dwr!!!}